[package]
name = "warp-git"
version = "0.1.0"
authors = ["k3d3 <k@3d3.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
